import pandas as pd
from os import mkdir, remove
from pathlib import Path
from glob import glob
from time import time

if __name__ == "__main__":

	
	name_prefix = "ILSVRC2012_model_metrics_"
	# Should sort by filename which is generated by timestamp
	model_metric_files = sorted(glob(str(f"../model_metrics/{name_prefix}*.csv")))

	for idx, metric_file in enumerate(model_metric_files):
		if idx == 0:
			# Create dataframe
			df = pd.read_csv(metric_file, index_col=0)
		else:
			df = df.append(pd.read_csv(metric_file, index_col=0))

	# Write aggregated dataframe to file.
	timestamp = str(pd.Timestamp.now()).replace(" ", "_").replace(":","").replace(".","")
	new_filename = name_prefix + timestamp + ".csv"

	df.to_csv(f"../model_metrics/combined_{new_filename}")




